---
- name: Install rpm dependencies
  yum: "name={{ item }} state=present"
  with_items:
    - git
    - packstack-modules-puppet

- { include: setup-openstack-elements.yml }
- { include: setup-tempest.yml }

- name: Run tempest
  script: run_tempest.sh {{ tempest['checkout_dir'] }} "{{ tempest_test_name }}"
       --exclude-files {{ tempest['exclude']['files'] }}
       --exclude-tests {{ tempest['exclude']['tests'] }}

- name: Fetch results
  fetch: src={{ tempest['checkout_dir']}}/nosetests.xml dest=nosetests.xml flat=yes
