---
# Steps
# =======
# - Provision *** take that out ***
# - Validate the nodes
# - Bootstrap: Prepare the slaves
# - Configure packstack answer-file
#       - apply rdo config
#       - apply multinode config
# - Deploy Openstack using packstack
# - Reboot all test-vms
# - Tempest slave
# - Run tempest [task]
# - Collect logs
# - CleanUp
#

### enable to provison vm
#- include: multinode/provision.yml

- include: multinode/validate-nodes.yml
- include: common/bootstrap.yml  tags=bootstrap

# apply pre-packstack workarouds
- include: multinode/icehouse/workarounds.yml tags=workaround

- name: Setup packstack on Controller
  hosts: controller
  roles:
      - packstack/rdo
      - packstack/multinode
  tags: generate-config

- include: multinode/setup-ssh-keys.yml tags=setup-trust


- name: Run packstack
  hosts: controller
  roles:
    - { role: packstack/runner }
  tags: run-packstack

- name: Reboot controller and compute
  hosts:
    - compute
    - controller
  tasks:
      - include: ../../tasks/common/reboot.yml
  tags: reboot

#- name: Setup tempest on Tempest slave
  #hosts: tempest
  #roles:
      #- { role: tempest }
  #tasks:
    #- { include: ../../tasks/openstack/run_tempest.yml }

#- name: Collect logs
  #hosts: local
  #roles:
      #- { role: log_collector }
