---
- name: Get nodes from nova
  hosts: local
  gather_facts: False
  roles:
    - { role: get_nodes }
  tags:
    - provision

- name: Set facts for hosts
  hosts: packstack
  gather_facts: False
  roles:
    - { role: set_facts }
    - { role: wait_for_hosts }
  tags:
    - provision

- include: common/bootstrap.yml tags=bootstrap

- name: packstack
  hosts: packstack
  vars:
    controller_name: "{{ ansible_ssh_host }}"
    controller_fqdn: "{{ ansible_ssh_host }}"
  roles:
    - { role: packstack/rdo }
    - { role: packstack/packstack-neutron-aio }
  tags:
    - prep

- name: Install packstack
  hosts: packstack
  vars:
    controller_name: "{{ ansible_ssh_host }}"
    controller_fqdn: "{{ ansible_ssh_host }}"
  roles:
    - { role: packstack/runner }
  tags:
    - install

- name: Run tempest
  hosts: packstack
  vars:
    controller_name: "{{ ansible_ssh_host }}"
    controller_fqdn: "{{ ansible_ssh_host }}"
  roles:
    - { role: tempest, controller_fqdn: "{{ controller_name }}", tags: ["tempest_run"] }
