---
- name: Get nodes from nova
  hosts: local
  gather_facts: False
  roles:
    - { role: get_nodes }
  tags:
    - provision

- name: Set facts for hosts
  hosts: packstack
  gather_facts: False
  roles:
    - { role: set_facts }
    - { role: wait_for_hosts }
  tags:
    - provision

- name: Prepare system for packstack
  hosts: packstack
  roles:
    - { role: common }
    - { role: linux-common }
  tags:
    - prep

# apply pre-packstack workarouds
- include: ../../workarounds/icehouse/workarounds-prep.yml tags=workaround

- name: Packstack prep
  hosts: packstack
  vars:
    controller_name: "{{ ansible_ssh_host }}"
    controller_fqdn: "{{ ansible_ssh_host }}"
  roles:
    - { role: packstack/rdo }
    - { role: packstack/packstack-neutron-aio }
  tags:
    - prep

# apply pre-packstack workarouds
- include: ../../workarounds/icehouse/workarounds-pre-run-packstack.yml tags=workaround

- name: Install packstack
  hosts: packstack
  vars:
    controller_name: "{{ ansible_ssh_host }}"
    controller_fqdn: "{{ ansible_ssh_host }}"
  roles:
    - { role: packstack/runner }
  tags:
    - run-packstack

  # apply post-packstack workarouds
- include: ../../workarounds/icehouse/workarounds-post-run-packstack.yml tags=workaround-post-install

- name: Update RPMs
  hosts: packstack
  roles:
    - { role: rdopkg/update, tags: ["rdoupdate"] }

- name: Run tempest
  hosts: tempest
  vars:
    controller_name: "{{ ansible_ssh_host }}"
    controller_fqdn: "{{ ansible_ssh_host }}"
  roles:
    - { role: tempest, controller_fqdn: "{{ controller_name }}", tags: ["tempest_run"] }

- name: Gather Logs
  hosts: packstack
  roles:
    - { role: collect_logs }
  tags:
    - collect_logs
