---
- name: Get nodes from nova
  hosts: local
  gather_facts: False
  roles:
    - { role: get_nodes }

- name: Set facts for hosts
  hosts: packstack
  gather_facts: False
  user: root
  roles:
    - { role: set_facts }
    - { role: wait_for_hosts }

- name: packstack
  hosts: packstack
  user: root
  roles:
    - { role: common }
    - { role: linux-common }
    - { role: packstack/packstack-common }
    - { role: packstack/rdo }
    - { role: packstack/packstack-rdopkg-neutron }
    - { role: packstack/packstack-installer }
    - { role: tempest }

