---
- name: Get nodes from nova
  hosts: local
  gather_facts: False
  roles:
    - { role: get_nodes }
  tags:
    - provision

- name: Set facts for hosts
  hosts: packstack
  gather_facts: False
  user: root
  roles:
    - { role: set_facts }
    - { role: wait_for_hosts }
  tags:
    - provision

- name: packstack
  hosts: packstack
  vars:
    controller_name: "{{ ansible_ssh_host }}"
    controller_fqdn: "{{ ansible_ssh_host }}"
  user: root
  roles:
    - { role: common }
    - { role: linux-common }
    - { role: packstack/packstack-common }
    - { role: packstack/rdo }
    - { role: packstack/packstack-rdopkg-neutron }
  tags:
    - prep

- name: Install packstack
  hosts: packstack
  vars:
    controller_name: "{{ ansible_ssh_host }}"
    controller_fqdn: "{{ ansible_ssh_host }}"
  user: root
  roles:
    - { role: packstack/packstack-installer }
  tags:
    - install

- name: Run tempest
  hosts: packstack
  vars:
    controller_name: "{{ ansible_ssh_host }}"
    controller_fqdn: "{{ ansible_ssh_host }}"
  user: root
  roles:
    - { role: tempest, controller_fqdn: "{{ controller_name }}" }
  tags:
    - tempest
