---
# installs packages from the rdopkg update_rpms repo.
  - name: Check if RPMs in update_rpms_dir
    shell: find . -regex '.*rpm' | wc -l  chdir={{ update_rpms_dir }}
    register: rpms_found

  - name: Install packages from rdopkg repo
    shell:  yum -y install * chdir={{ update_rpms_dir }}
    when: rpms_found.stdout | int > 0
    register: rdo_result

  - name: print result of RPM install
    debug: var=rdo_result.stdout_lines
    when: rdo_result is defined
