---
# installs packages from the rdopkg update_rpms repo.
  - name: Install packages from rdopkg repo
    shell:  yum -y install * chdir={{ update_rpms_dir }}
    register: result

  - name: print result of packstack install
    debug: var=result.stdout_lines

  - name: run migration for neutron service
    sudo: yes
    shell: "openstack-db --service {{ item }} --update"
    when: product.version == 'juno'
    with_items:
      - neutron
      - nova

  - name: Reboot after package install
    debug: msg=rebooting
    when: result.rc == 0
    changed_when: True
    notify:
    - reboot
    - Wait for host to stop
    - Wait for host to come back
