---
- name: Provision nodes
  nova_compute:
       auth_url: "{{ os_auth_url }}"
       state: present
       login_username: "{{ os_username }}"
       login_password: "{{ os_password }}"
       login_tenant_name: "{{ os_tenant_name }}"
       name: "{{ item.name }}"
       image_id: "{{ item.image_id }}"
       key_name: "{{ item.key_name }}"
       wait_for: 200
       flavor_id: "{{ item.flavor_id }}"
       nics: "{{ item.network_ids }}"
  register: snap_nodes
  with_items: nodes

- name: dump network and node info
  debug: msg="{{ item }}"
  with_together:
    - wait_snapshot
    - wait_for
  when: "'debug' in config.verbosity"

- name: create snapshot of environment
  nova_snapshot:
       auth_url: "{{ os_auth_url }}"
       state: present
       login_username: "{{ os_username }}"
       login_password: "{{ os_password }}"
       login_tenant_name: "{{ os_tenant_name }}"
       instance_name: "{{ item.name }}"
       snapshot_name: "{{ item.name }}-snap"
       wait_snapshot: "{{ wait_snapshot }}"
       wait_for: "{{ wait_for }}"
  register: snapshot_id
  with_items: nodes
  when: snapshot_name is not defined

- name: create named snapshot of environment
  nova_snapshot:
       auth_url: "{{ os_auth_url }}"
       state: present
       login_username: "{{ os_username }}"
       login_password: "{{ os_password }}"
       login_tenant_name: "{{ os_tenant_name }}"
       instance_name: "{{ item.name }}"
       snapshot_name: "{{ snapshot_name }}"
       wait_snapshot: "{{ wait_snapshot }}"
       wait_for: "{{ wait_for }}"
  register: snapshot_id
  with_items: nodes
  when: snapshot_name is defined

- debug: msg={{ snapshot_id }}

# - name: Provision Snapshotted nodes
#   nova_compute:
#        auth_url: "{{ os_auth_url }}"
#        state: present
#        login_username: "{{ os_username }}"
#        login_password: "{{ os_password }}"
#        login_tenant_name: "{{ os_tenant_name }}"
#        name: "{{ snapshot_name }}"
#        image_id: "{{ item }}"
#        key_name: "{{ item.key_name }}"
#        wait_for: 200
#        flavor_id: "{{ item.flavor_id }}"
#        nics: "{{ item.network_ids }}"
#   with_items: snapshot_id.results

# - name: Assign floating ip
#   neutron_floating_ip:
#        auth_url: "{{ os_auth_url }}"
#        state: present
#        login_username: "{{ os_username }}"
#        login_password: "{{ os_password }}"
#        login_tenant_name: "{{ os_tenant_name }}"
#        network_name: "{{ floating_network_name }}"
#        instance_name: "{{ snapshot_name }}"
#        internal_network_name: default
#   register: floating_ips
#   with_items: snap_nodes

# - name: dump network and node info
#   debug: msg="{{ item }}"
#   with_together:
#     - snap_nodes.results
#     - floating_ips.results
#   when: "'debug' in config.verbosity"
