---
- name: remove {{ tempest.dir }}/.testrepository
  file: path={{ tempest.dir }}/.testrepository state=absent
  tags: tempest_run

- name: Run tempest
  script: run_tempest.sh {{ tempest.dir }} {{ tempest.test_name }}
       --exclude-files {{ tempest.skip.files }}
       --exclude-tests {{ tempest.skip.tests }}
  tags: tempest_run
  ignore_errors: True

- name: Fetch results
  fetch: src={{ tempest.dir }}/nosetests.xml
         dest=nosetests.xml flat=yes
  tags: tempest_run
