---
- name: Remove the EPEL Repository.
  yum: name=epel-release state=removed
  when: ansible_distribution == "RedHat"

- name: Yum clean all
  command: yum clean all
  when: ansible_distribution == "RedHat"

- name: Create ssh key if one does not exist
  #this will not overwrite an existing key
  user: name=root generate_ssh_key=yes
  sudo: yes
  sudo_user: root
  tags: setup-keys

- name: add id_rsa to authorized_keys
  shell: cat /root/.ssh/id_rsa.pub >> /root/.ssh/authorized_keys
  sudo: yes
  sudo_user: root
  tags: setup-keys

# workaround {
- name: WORKAROUND | BZ | Ensure iptables is running
  service: name=iptables state=started
  tags: workaround
  when: workarounds_disabled is not defined or
        workarounds_disabled|bool == false
# }

