---
- name: Update yum on all nodes before packstack installation
  hosts: openstack_nodes
  gather_facts: no
  sudo: yes
  tasks:
      - name: Update all packages
        yum: name=* state=latest

- name: Setup packstack on controller
  hosts: controller
  gather_facts: no
  sudo: yes
  tasks:
      - name: Install packstack package
        yum: name=openstack-packstack state=present

      - name: Generate answer file
        shell: "packstack --gen-answer-file={{ installer.packstack.answer_file }} --provision-demo=n"

      - name: Update answer file with default password
        command:
          sed
              -e 's|_PASSWORD=.*|_PASSWORD=redhat|'
              -e 's|_PW=.*|_PW=redhat|'
              -i /root/{{ installer.packstack.answer_file }}

      - name: Running packstack
        shell: "packstack --answer-file=/root/{{ installer.packstack.answer_file }} && touch /root/packstack-already-done"
        args:
          creates: /root/packstack-already-done
        register: result
