---
- name: restart ntpd
  service: name=ntpd state=restarted

- include: ../../../tasks/common/reboot.yml

- name: Reload facts
  action: setup

- name: Yum clean all
  command: yum clean all

- name: yum -y update to latest packages
  yum: name=* state=latest
  notify:
      - reboot
      - Wait for host to stop
      - Wait for host to come back
      - Reload facts

- name: restart network
  service: name=network state=restarted
