---
  - name: rdopkg directory present
    file: path={{ rdopkg_rpm_dir }} owner=root group=root state=directory

  - name: clear rdopkg directory
    command: rm -Rf {{ rdopkg_rpm_dir }}/*

  - name: copy update_rpms_tarball to node
    copy: src={{ update_rpms_tarball }} dest={{ rdopkg_rpm_dir }} owner=root group=root mode=0644

  - name: unpack update_rpms_tarball
    shell: find {{ rdopkg_rpm_dir }} -regex '.*.tar.gz' | xargs tar -xvz -C {{ rdopkg_rpm_dir }} -f

  - name: rpm force install rdopkg RPMs
    shell: find {{ rdopkg_rpm_dir }} -regex '.*rpm' | xargs rpm -i --force --nodeps

  - name: restart openstack and neutron services
    service: name={{ item }} state=restarted
    with_items:
      services_list