---
  - name: Ensure createrepo
    yum: name=createrepo state=present

  - name: rdopkg directory present
    file: path={{ update_rpms_dir }} owner=root group=root state=directory

  - name: clear rdopkg directory
    command: rm -Rf {{ update_rpms_dir }}/*

  - name: copy update_rpms_tarball to node
    copy: src={{ update_rpms_tarball }} dest={{ update_rpms_dir }} owner=root group=root mode=0644

  - name: unpack update_rpms_tarball
    shell: find {{ update_rpms_dir }} -regex '.*.tar.gz' | xargs tar -xvz -C {{ update_rpms_dir }} -f

  - name: createrepo in update rpms dir
    command: createrepo {{ update_rpms_dir }} 

  - name: Create the update rpms repo
    template: src=update_rpms.repo.j2 dest=/etc/yum.repos.d/update_rpms.repo
    notify:
    - Yum clean all
    - yum -y update to latest packages
