- name: reboot
  command: /sbin/shutdown -r {{ reboot_delay | default('+1') }} 'Reboot is triggered by Ansible'

- name: Wait for host to stop
  local_action: "wait_for host={{ hostvars[inventory_hostname].ansible_ssh_host }} port=22 state=stopped"
  sudo: false

- name: Wait for host to come back
  local_action: "wait_for host={{ hostvars[inventory_hostname].ansible_ssh_host }} port=22 delay=90 timeout=600"
  sudo: false

- name: Reload facts
  action: setup
