---
#CENTOS

- name: Ensure centos-release
  yum: name=centos-release state=present

- name: Remove all yum repositories
  file: path=/etc/yum.repos.d/{{ item }} state=absent
  with_items: repos_to_remove
  notify:
    - Yum clean all

- name: Create the CentOS Repositories
  template: src=CentOS-Base.repo.j2 dest=/etc/yum.repos.d/CentOS-Base.repo
  notify:
    - Yum clean all
    - yum -y update to latest packages

- name: Create the EPEL Repository
  template: src=epel.repo.j2 dest=/etc/yum.repos.d/epel.repo
  notify:
    - Yum clean all
    - yum -y update to latest packages

- name: Ensure httplib2
  yum: name=python-httplib2 state=present

