---
- name: Install tempest from rpm
  hosts: tester
  gather_facts: no
  sudo: yes
  tasks:
    # Normally tempest would be already available from the installer repos
    # but that's not the case yet (master pkg now needs kilo rdo for deps)
    - command: yum localinstall -y https://rdo.fedorapeople.org/openstack-kilo/rdo-release-kilo.rpm
      when: tester.rpm.release == 'master' and provisioner.type != 'centosci'
    # and atm also custom delorean repo (until it gets into trunk.rdo)
    - template: dest=/etc/yum.repos.d/tempest.repo src=../templates/tempest-master.repo owner=root group=root mode=0644
      register: tempest_repo
      when: tester.rpm.release == 'master' and provisioner.type != 'centosci'

    - command: yum clean all
      when: tempest_repo|changed

    - yum: name=openstack-tempest state=present
      register: tempest_rpm

    - command: rpm -q --qf %{VERSION} openstack-tempest
      register: tempest_rpm_version

    - command: rpm -q --qf %{RELEASE} openstack-tempest
      register: tempest_rpm_release


    - debug: "msg='Build mark: tempest={{ tempest_rpm_version.stdout }}-{{ tempest_rpm_release.stdout }}'"

    # TODO(psedlak): make subunit2junitxml usage opt. in script, add the flag for run-tests.sh in run.yml after that
    - yum: name=subunit-filters state=present # needed for subunit2junitxml

- name: Initialize tempest workspace directory for regular user
  hosts: tester
  gather_facts: no
  tasks:
    - file: dest={{ tester.dir }} state=directory
    - command: /usr/share/openstack-tempest-{{ tempest_rpm_version.stdout }}/tools/configure-tempest-directory
      args:
        chdir: "~/{{ tester.dir }}"
        creates: "~/{{ tester.dir }}/LICENSE"
