---
- name: prep rdo on tempest
  hosts: tempest:&RedHat:!skip_prep
  sudo: yes
  roles:
    - { role: linux/rhel/rdo }
  tags:
    - prep

- name: Prepare system for packstack
  hosts: all:!localhost:!skip_prep
  sudo: yes
  roles:
    - { role: common }
  tags:
    - prep

- name: RHEL RHOS prep
  hosts: all:!localhost:&RedHat:&rhos:!skip_prep
  sudo: yes
  roles:
    - { role: linux/rhel/rhos }
  tags:
    - prep

- name: RHEL RDO prep
  hosts: all:!localhost:&RedHat:&rdo:!skip_prep
  sudo: yes
  roles:
    - { role: linux/rhel/rdo }
  tags:
    - prep

- name: CentOS RDO prep
  hosts: all:!localhost:&CentOS:&rdo:!skip_prep
  sudo: yes
  roles:
    - { role: linux/centos }
  tags:
    - prep

- name: Fedora RDO prep
  hosts: all:!localhost:&Fedora:&rdo:!skip_prep
  sudo: yes
  roles:
    - { role: linux/fedora }
  tags:
    - prep

- name: Linux common prep
  hosts: all:!localhost:!skip_prep
  sudo: yes
  roles:
    - { role: linux-common }
  tags:
    - prep

