---
# provison
- include: dump_settings.yml
- include: provision.yml
- include: group_by.yml tags=provision

- name: Prepare network for Packstack install
  sudo: yes
  hosts:
    - controller
    - compute
  tags: prep
  roles:
    -  network-setup

- include: validate_nodes.yml

- name: Debug list config variables
  hosts: local
  sudo: no
  tags: provision
  roles:
    - { role: packstack/debug }

# prep
- include: packstack/setup-ssh-keys.yml tags=prep
- include: prep.yml

# apply pre-packstack workarouds
- include: ../workarounds/workarounds-prep.yml tags=workaround

- name: Setup packstack on Controller (rdo)
  hosts: controller:&rdo
  sudo: yes
  roles:
      - product/rdo
  tags: prep

- name: Setup packstack on Controller (rhos)
  hosts: controller:&rhos
  sudo: yes
  roles:
      - product/rhos
  tags: prep

# Generate answers
- name: Setup packstack on Controller
  hosts: controller
  sudo: yes
  roles:
      - packstack/generate-answers
  tags: prep

- name: Update RPMs (rdopkg)
  hosts: controller
  sudo: yes
  roles:
    - { role: rdopkg/prep, tags: ["rdoupdate-preinstall"] }
    - { role: rdopkg/preinstall, tags: ["rdoupdate-preinstall"] }

- include: ../workarounds/workarounds-pre-run-packstack.yml tags=workaround

# packstack_run

- name: Run packstack
  hosts: controller
  sudo: yes
  roles:
    - { role: packstack/runner }
  tags: packstack_run

- include: ../workarounds/workarounds-post-run-packstack.yml tags=workaround

- name: Update RPMs on controller
  hosts: controller
  sudo: yes
  roles:
    - { role: rdopkg/prep, tags: ["rdoupdate"] }
    - { role: rdopkg/postinstall, tags: ["rdoupdate"] }

- name: Update RPMs on tempest node
  hosts: tempest
  sudo: yes
  roles:
    - { role: rdopkg/prep, tags: ["rdoupdate-tempest"] }
    - { role: rdopkg/postinstall, tags: ["rdoupdate-tempest"] }

- name: Get Status after reboot
  hosts: controller
  sudo: yes
  tags: openstack_status
  roles:
    - { role: openstack/openstack-status }

# sahara
- include: sahara.yml

# tempest
- name: List ip address of tempest node
  hosts: tempest
  sudo: yes
  roles:
    - { role: tempest/iptables/node_data }
  tags: tempest_setup

- name: Ensure iptables is open for tempest
  hosts: all:!localhost:!tempest
  sudo: yes
  roles:
    - { role: tempest/iptables }
  tags: tempest_setup

- include: tempest.yml

- name: SELINUX error check
  hosts: all:!localhost:!tempest
  sudo: yes
  roles:
    - { role: selinux_check }
  tags: provision

- name: RHOS SELINUX error check
  hosts: all:!localhost:!tempest:&rhos
  sudo: yes
  roles:
    - { role: selinux_check/rhos }
  tags: provision

